### ISSUE TITLE
Move this repo to the JuliaHealth organization

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaHealth/DICOM.jl#48]
Any objection to moving this repo to the JuliaHealth organization?

cc: @notZaki 
cc: @ViralBshah

**Comment by ViralBShah** [comment]
I think @notZaki being the maintainer should decide what's best.

**Comment by notZaki** [comment]
I don't have any objection.

Would other packages, like [NIfTI.jl](https://github.com/JuliaIO/NIfTI.jl), also be moving?

**Comment by DilumAluthge** [comment]
I am happy to accept all health/medicine/medical imaging packages that you would be willing to transfer :)

**Comment by DilumAluthge** [comment]
Looks like @simonster is the main contributor to https://github.com/JuliaIO/NIfTI.jl

**Comment by DilumAluthge** [comment]
In the meantime, @notZaki you should have the permissions to transfer this repo to JuliaHealth.

I'll open a new issue to discuss NIfTI.

**Comment by notZaki** [comment]
I don't think I can transfer the repository because I only have commit access here.

**Comment by DilumAluthge** [comment]
@ViralBShah do you have the permissions?

If not, maybe @ararslan does?

**Comment by ViralBShah** [comment]
I don't have owner access either. Maybe @ararslan does?

**Comment by DilumAluthge** [comment]
Looks like we simultaneously had the same tgough

**Comment by ararslan** [comment]
I do here but not JuliaHealth.

**Comment by SimonDanisch** [comment]
I guess I now have the correct rights and could transfer it ;)

**Comment by DilumAluthge** [comment]
@ararslan @SimonDanisch I think you both should have the correct permissions on JuliaHealth.

**Comment by DilumAluthge** [comment]
This is done.

If anyone needs an invite to JuliaHealth, just let me know.
