### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaHealth/DICOM.jl#53]
@notZaki What do you think about making a new release? Looks like a couple of bugs have been fixed since the last release?

**Comment by notZaki** [comment]
I have no objection to making a release right now. 

I was going to add two more things, namely:
- Function for parsing all DICOM files in a folder
- Extracting structures from DICOM RT files

but there's no harm in making a release from the current master.

**Comment by DilumAluthge** [comment]
I think it's fine to wait until you add those features to make the next release!
