### ISSUE TITLE
sequence_item returned type

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaHealth/DICOM.jl#77]
Could `sequence_item` return something like `DICOMData` instead of a plain `Dict`? This way it could support accessing elements using `getproperty` like `DICOMData`.

**Comment by notZaki** [comment]
I like this idea, it would definitely be elegant to access the sequence like that.

I don't think I'll be able to work on this during the current month, but if anyone else feels like implementing this, then feel free.
